import psycopg2
db = psycopg2.connect('test.db')
db.execute("CREATE TABLE users (id INTEGER PRIMARY KEY, username CHAR NOT NULL, password CHAR NOT NULL);")
db.execute("INSERT INTO users(username, password) VALUES ('trace','tr4c3');")
db.execute("INSERT INTO users(username, password) VALUES ('trace1','tr4c3');")
db.execute("INSERT INTO users(username, password) VALUES ('tina','t1na');")
db.execute("INSERT INTO users(username, password) VALUES ('verdi','v3rdi');")
db.execute("CREATE TABLE students (id INTEGER PRIMARY KEY, name CHAR NOT NULL, address CHAR, birthyear INTEGER , faculty CHAR);")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Trace','Hue', 1995, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Crystal','Dak Lak', 1995, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Na','Da Nang', 1995, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Philip','Hue', 1994, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Tina','Ha Tinh', 1995, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Nickie','Da Nang', 1995, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Nathan','Quang Ngai', 1995, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Darick','Quang Nam', 1995, 'IT');")
db.execute("INSERT INTO students(name, address, birthyear, faculty) VALUES ('Harley','Quang Tri', 1995, 'IT');")
db.commit()
